#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJ_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
TMP_DIR="${PROJ_ROOT}/.tmp/coverage"
REPORT_PATH="${PROJ_ROOT}/reference/coverage_report.md"

CRATE_LINE_MIN="${CRATE_LINE_MIN:-92.0}"
CRATE_FUNCTION_MIN="${CRATE_FUNCTION_MIN:-90.0}"
WORKSPACE_LINE_MIN="${WORKSPACE_LINE_MIN:-85.0}"

mkdir -p "${TMP_DIR}"

JSON_PATH="${TMP_DIR}/workspace_coverage.json"

(
    cd "${PROJ_ROOT}"
    cargo llvm-cov --workspace --all-features --json --output-path "${JSON_PATH}" >/dev/null
)

python3 - "${JSON_PATH}" "${REPORT_PATH}" "${CRATE_LINE_MIN}" "${CRATE_FUNCTION_MIN}" "${WORKSPACE_LINE_MIN}" <<'PY'
import json
import sys
from pathlib import Path

json_path = Path(sys.argv[1])
report_path = Path(sys.argv[2])
crate_line_min = float(sys.argv[3])
crate_fn_min = float(sys.argv[4])
workspace_line_min = float(sys.argv[5])

doc = json.loads(json_path.read_text())
payload = doc["data"][0]

workspace_lines = payload["totals"]["lines"]["percent"]

crate_prefix = "/crates/libsvm/src/"
crate_line_total = 0
crate_line_covered = 0
crate_fn_total = 0
crate_fn_covered = 0

for file in payload["files"]:
    if crate_prefix not in file["filename"]:
        continue
    line_summary = file["summary"]["lines"]
    fn_summary = file["summary"]["functions"]
    crate_line_total += int(line_summary["count"])
    crate_line_covered += int(line_summary["covered"])
    crate_fn_total += int(fn_summary["count"])
    crate_fn_covered += int(fn_summary["covered"])

crate_lines = 100.0 * crate_line_covered / crate_line_total
crate_functions = 100.0 * crate_fn_covered / crate_fn_total

threshold_results = [
    ("libsvm-rs line coverage", crate_lines, crate_line_min),
    ("libsvm-rs function coverage", crate_functions, crate_fn_min),
    ("workspace line coverage", workspace_lines, workspace_line_min),
]

failures = []
for name, value, minimum in threshold_results:
    if value + 1e-12 < minimum:
        failures.append((name, value, minimum))

report = [
    "# Coverage Report",
    "",
    "Generated by `scripts/check_coverage_thresholds.sh`.",
    "",
    "## Metrics",
    "",
    f"- `libsvm-rs` line coverage: `{crate_lines:.2f}%` (target `>= {crate_line_min:.2f}%`)",
    f"- `libsvm-rs` function coverage: `{crate_functions:.2f}%` (target `>= {crate_fn_min:.2f}%`)",
    f"- Workspace line coverage: `{workspace_lines:.2f}%` (target `>= {workspace_line_min:.2f}%`)",
    "",
    "## Status",
    "",
]

if failures:
    report.append("- `FAIL`")
else:
    report.append("- `PASS`")

report_path.write_text("\n".join(report) + "\n")

for line in report[5:9]:
    print(line)

if failures:
    for name, value, minimum in failures:
        print(f"ERROR: {name} {value:.2f}% is below {minimum:.2f}%", file=sys.stderr)
    sys.exit(1)
PY

echo "Wrote ${REPORT_PATH}"
